version: '3.8'
services:
  client:
    build: ./frontend/
    image: khaledgs/secure_ci_cd_pipeline_client
    container_name: footfront
    ports:
      - "4200:4200"
    command: ng serve --host 0.0.0.0
    volumes:
      - "./frontend/:/app"
      - "/app/node_modules"
    depends_on:
      - server

  server:
    build: ./nodejs-express-mongodb/
    image: khaledgs/secure_ci_cd_pipeline_server
    container_name: footback
    ports:
      - "8081:8081"
    command: npm run server
    env_file:
      - .env
    volumes:
      - "./nodejs-express-mongodb/:/app"
      - "/app/node_modules"
    depends_on:
      - db

  db:
    image: mongo:4.4
    container_name: footdb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - db-data:/data/db

volumes:
  db-data: {}
