apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: secure-ci-cd-pipeline-server
  replicas: 2
  template:
    metadata:
      labels:
        app: secure-ci-cd-pipeline-server
    spec:
      containers:
      - name: secure-ci-cd-pipeline-server
        image: khaledgs/secure_ci_cd_pipeline_server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: mongo-url
        securityContext:
          runAsNonRoot: true            # Ensures the container does not run as root
          runAsUser: 1000               # Set a non-root user ID
          readOnlyRootFilesystem: true  # Makes the root filesystem read-only
          allowPrivilegeEscalation: false  # Prevents privilege escalation
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30001
  selector:
    app: secure-ci-cd-pipeline-server

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  # Ensure the MongoDB URI is Base64 encoded
  mongo-url: bW9uZ29kYitzcnY6Ly9raGFsZWRnYXNzYXJhOm9DME1JVmwwR1ExZnJtUGtAY2x1c3RlcjAuN2hid3QubW9uZ29kYi5uZXQv
